# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-27 00:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211208_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=1000, verbose_name='ФИО')),
                ('email', models.CharField(max_length=1000, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('date', models.DateField(verbose_name='Дата')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'Orders',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 27, 3, 58, 59, 186164), verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 27, 3, 58, 59, 186164), verbose_name='Дата'),
        ),
    ]
