# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-28 04:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211228_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 28, 7, 27, 21, 592306), verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 28, 7, 27, 21, 593306), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.CharField(max_length=1000, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sum',
            field=models.IntegerField(null=True, verbose_name='Сумма'),
        ),
    ]
