# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-28 05:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211228_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='tickets',
            field=models.TextField(null=True, verbose_name='Билеты'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 28, 8, 42, 43, 604214), verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 28, 8, 42, 43, 605214), verbose_name='Дата'),
        ),
    ]
